on:
  workflow_dispatch:
  schedule:
    - cron: "17 17 10,20 * *"

permissions:
  contents: write
  pull-requests: write

env:
  USER_AGENT: ${{ secrets.USER_AGENT }}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        # Required for git-auto-commit-action.
        persist-credentials: true

    - name: Fetching new entries
      run: go run main.go

    - name: Push any updates
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit-message: Updating etfs data
        branch: main
        file-pattern: 'data/*.json'
